# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.debug=false

# Build Properties
maven_group=me.ayydxn
archives_name=teleidoscope

# Mod Properties
mod_name=Teleidoscope
mod_version=1.0.0
mod_id=teleidoscope
mod_description=A free and open-source utility mod for Minecraft that lets you seamlessly open singleplayer worlds to your friends via Steam Networking.
mod_authors=Ayydxn
sources_url=https://github.com/Ayydxn/Teleidoscope
issue_tracker_url=https://github.com/Ayydxn/Teleidoscope/issues
license=LGPL-3.0-or-later
icon_path=icon.png

# Minecraft Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
parchment_version=2023.09.03
enabled_platforms=fabric,forge

# Fabric Properties
# Check these on https://fabricmc.net/develop
fabric_api_version=0.92.11+1.20.1
fabric_loader_version=0.19.3

# Forge Properties
# Check these on https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=1.20.1-47.4.10
forge_version_range=[47,)

# Architectury Properties
architectury_api_version=9.2.14
architectury_version_range=[9.2,)

# Mod Dependencies
modmenu_version=7.2.2
yacl_version=3.6.6+1.20.1
yacl_version_range=[3.6.6+1.20.1,)
